### ISSUE TITLE
node errors after running npm start - Error generating dev certificate

### ISSUE THREAD

**Issue by rossmc** [magento-research/venia-pwa-concept#51]
I followed the steps in the README and was able to set up Magento fine, with the venia theme configured and working to display a blank page with the contents of _root.phtml_.

I also set up a _theme-frontend-venia/.env_ file.

Although when I tried to run `npm start` I get an `Error: Cannot find module '@jzetlen/pwa-buildpack'`

Changing the webpack.config.js to use `@magento/pwa-buildpack`  rather than `@jzetlen/pwa-buildpack` removed this error but then I got another error after running `npm start` and being prompted for my password.

```
(node:22028) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Command failed: /usr/local/bin/node /Users/ross/Projects/venia-pwa-concept/theme-frontend-venia/node_modules/@magento/pwa-buildpack/dist/util/tmpb1jhh3d488958 && rm /Users/ross/Projects/venia-pwa-concept/theme-frontend-venia/node_modules/@magento/pwa-buildpack/dist/util/tmpb1jhh3d488958
module.js:491
    throw err;
    ^

Error: Cannot find module '/Users/ross/Projects/venia-pwa-concept/theme-frontend-venia/node_modules/@magento/pwa-buildpack/dist/util/tmpb1jhh3d488958'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:578:3
```
After reading over the [PWA Buildpack README](https://github.com/magento-research/pwa-buildpack) I tried installing these dependencies which seemed to be missing...

```
npm install --save-dev @magento/pwa-buildpack \
babel-core babel-loader babel-helper-module-imports \
babel-plugin-syntax-jsx babel-plugin-transform-class-properties \
babel-plugin-transform-object-rest-spread babel-plugin-transform-react-jsx \
webpack@3 webpack-dev-server@2
```
Although this leads to more warnings and errors after running `npm start` and being prompted for my password.  Seemingly from the [sudo-prompt](https://github.com/jorangreef/sudo-prompt) dependency

```
Error: Cannot find module '/Users/ross/Projects/venia-pwa-concept/theme-frontend-venia/node_modules/@magento/pwa-buildpack/dist/util/tmpif6c4b6986408'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:578:3
```
AND
```
Error: [pwa-buildpack:util:ssl-cert-store.js] Error generating dev certificate: Command failed: /usr/local/bin/node /Users/ross/Projects/venia-pwa-concept/theme-frontend-venia/node_modules/@magento/pwa-buildpack/dist/util/tmp2h4719i7277ea && rm /Users/ross/Projects/venia-pwa-concept/theme-frontend-venia/node_modules/@magento/pwa-buildpack/dist/util/tmp2h4719i7277ea
module.js:491
    throw
```

FYI - working on osx with node v8.3.0

**Comment by eswolters** [comment]
I have the same isue, but I am stil using the @jzetlen/pwa-buildpack.

**Comment by zetlen** [comment]
Sorry, I left my fork of buildpack in the webpack config somehow. I've pushed an update to master. Normally I wouldn't, but our team is too scattered during Imagine for proper process.

@rossmc Can you try it now?

**Comment by rossmc** [comment]
@zetlen thanks for the quick response, I appreciate you're probably busy with Imagine.

I'm afraid it did not work after I pulled down your changes, no need to respond right away on this, I presume you have your hands full with Imagine.

Any way still getting the same error:

```
ross in ~/Projects/venia-pwa-concept/theme-frontend-venia
$ (master) rm -rf node_modules/ ; git checkout package-lock.json
ross in ~/Projects/venia-pwa-concept/theme-frontend-venia
$ (master) npm install

> fsevents@1.2.0 install /Users/ross/Projects/venia-pwa-concept/theme-frontend-venia/node_modules/fsevents
> node install

[fsevents] Success: "/Users/ross/Projects/venia-pwa-concept/theme-frontend-venia/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> uglifyjs-webpack-plugin@0.4.6 postinstall /Users/ross/Projects/venia-pwa-concept/theme-frontend-venia/node_modules/webpack/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js


> theme-frontend-venia@0.1.0 prepare /Users/ross/Projects/venia-pwa-concept/theme-frontend-venia
> npm-merge-driver install

npm-merge-driver: npm-merge-driver installed to `git config --local` and /Users/ross/Projects/venia-pwa-concept/.git/info/attributes
added 1637 packages in 19.169s
ross in ~/Projects/venia-pwa-concept/theme-frontend-venia
$ (master) npm start

> theme-frontend-venia@0.1.0 start /Users/ross/Projects/venia-pwa-concept/theme-frontend-venia
> webpack-dev-server --progress --color --env.phase development

Error: [pwa-buildpack:util:ssl-cert-store.js] Error generating dev certificate: Command failed: /usr/local/bin/node /Users/ross/Projects/venia-pwa-concept/theme-frontend-venia/node_modules/@magento/pwa-buildpack/dist/util/tmp62fa5fg5804hh && rm /Users/ross/Projects/venia-pwa-concept/theme-frontend-venia/node_modules/@magento/pwa-buildpack/dist/util/tmp62fa5fg5804hh
module.js:491
    throw err;
    ^

Error: Cannot find module '/Users/ross/Projects/venia-pwa-concept/theme-frontend-venia/node_modules/@magento/pwa-buildpack/dist/util/tmp62fa5fg5804hh'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:578:3
 Error: Command failed: /usr/local/bin/node /Users/ross/Projects/venia-pwa-concept/theme-frontend-venia/node_modules/@magento/pwa-buildpack/dist/util/tmp62fa5fg5804hh && rm /Users/ross/Projects/venia-pwa-concept/theme-frontend-venia/node_modules/@magento/pwa-buildpack/dist/util/tmp62fa5fg5804hh
module.js:491
    throw err;
    ^

Error: Cannot find module '/Users/ross/Projects/venia-pwa-concept/theme-frontend-venia/node_modules/@magento/pwa-buildpack/dist/util/tmp62fa5fg5804hh'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:578:3

    at /Users/ross/Projects/venia-pwa-concept/theme-frontend-venia/node_modules/sudo-prompt/index.js:329:27
    at tryToString (fs.js:513:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:501:12)
    at Object.create (/Users/ross/Projects/venia-pwa-concept/theme-frontend-venia/node_modules/@magento/pwa-buildpack/dist/util/ssl-cert-store.js:44:19)
    at <anonymous>
```

I thought also tried running the npm commands in the linked magento dir on my host machine and the vagrant box, but that didn't work either.

**Comment by jorkvist** [comment]
`Mikaels-MBP-2:theme-frontend-venia jorkvist$ DEBUG=pwa-buildpack:WebpackTools:*,pwa-buildpack:util:run-as-root.js npm start

> theme-frontend-venia@0.1.0 start /Users/jorkvist/PWARIBATEX/venia-pwa-concept/theme-frontend-venia
> webpack-dev-server --progress --color --env.phase development

  pwa-buildpack:WebpackTools:PWADevServer.js configure() invoked { publicPath: '/Users/jorkvist/PWARIBATEX/vagrant-magento/magento2ce/pub/static/frontend/Magento/venia/en_US',
  backendDomain: 'https://magento2.vagrant89',
  serviceWorkerFileName: 'sw.js',
  paths: 
   { src: '/Users/jorkvist/PWARIBATEX/venia-pwa-concept/theme-frontend-venia/src',
     assets: '/Users/jorkvist/PWARIBATEX/venia-pwa-concept/theme-frontend-venia/web',
     output: '/Users/jorkvist/PWARIBATEX/venia-pwa-concept/theme-frontend-venia/web/js' },
  id: 'magento-venia' } +0ms
  pwa-buildpack:WebpackTools:PWADevServer.js provideDevHost('magento-venia') +3ms
  pwa-buildpack:WebpackTools:PWADevServer.js checking if magento-venia.local.pwadev is loopback +5ms
  pwa-buildpack:util:run-as-root.js elevating privileges for async name => {
  pwa-buildpack:util:run-as-root.js                 const devcert = require('@magento/devcert');
  pwa-buildpack:util:run-as-root.js                 const certs = await devcert(name);
  pwa-buildpack:util:run-as-root.js                 process.stdout.write(JSON.stringify(certs));
  pwa-buildpack:util:run-as-root.js             } +0ms
  pwa-buildpack:util:run-as-root.js running sudoPrompt("/Users/jorkvist/.nvm/versions/node/v8.5.0/bin/node /Users/jorkvist/PWARIBATEX/venia-pwa-concept/theme-frontend-venia/node_modules/@jzetlen/pwa-buildpack/dist/util/tmpib0fh061188d && rm /Users/jorkvist/PWARIBATEX/venia-pwa-concept/theme-frontend-venia/node_modules/@jzetlen/pwa-buildpack/dist/util/tmpib0fh061188d") now... +0ms
  pwa-buildpack:WebpackTools:PWADevServer.js setting magento-venia.local.pwadev loopback in /etc/hosts, may require password... +11ms
  pwa-buildpack:util:run-as-root.js elevating privileges for d => require('hostile').set('127.0.0.1', d) +10ms
  pwa-buildpack:util:run-as-root.js running sudoPrompt("/Users/jorkvist/.nvm/versions/node/v8.5.0/bin/node /Users/jorkvist/PWARIBATEX/venia-pwa-concept/theme-frontend-venia/node_modules/@jzetlen/pwa-buildpack/dist/util/tmp7dd8habgbjggd && rm /Users/jorkvist/PWARIBATEX/venia-pwa-concept/theme-frontend-venia/node_modules/@jzetlen/pwa-buildpack/dist/util/tmp7dd8habgbjggd") now... +0ms
  pwa-buildpack:util:run-as-root.js sudo /Users/jorkvist/.nvm/versions/node/v8.5.0/bin/node /Users/jorkvist/PWARIBATEX/venia-pwa-concept/theme-frontend-venia/node_modules/@jzetlen/pwa-buildpack/dist/util/tmp7dd8habgbjggd && rm /Users/jorkvist/PWARIBATEX/venia-pwa-concept/theme-frontend-venia/node_modules/@jzetlen/pwa-buildpack/dist/util/tmp7dd8habgbjggd returned { error: 
   { Error: Command failed: /Users/jorkvist/.nvm/versions/node/v8.5.0/bin/node /Users/jorkvist/PWARIBATEX/venia-pwa-concept/theme-frontend-venia/node_modules/@jzetlen/pwa-buildpack/dist/util/tmp7dd8habgbjggd && rm /Users/jorkvist/PWARIBATEX/venia-pwa-concept/theme-frontend-venia/node_modules/@jzetlen/pwa-buildpack/dist/util/tmp7dd8habgbjggd
   module.js:473
         throw err;
         ^
   
   Error: Cannot find module '/Users/jorkvist/PWARIBATEX/venia-pwa-concept/theme-frontend-venia/node_modules/@jzetlen/pwa-buildpack/dist/util/tmp7dd8habgbjggd'
       at Function.Module._resolveFilename (module.js:527:15)
       at Function.Module._load (module.js:453:25)
       at Function.Module.runMain (module.js:665:10)
       at startup (bootstrap_node.js:201:16)
       at bootstrap_node.js:626:3
   
       at /Users/jorkvist/PWARIBATEX/venia-pwa-concept/theme-frontend-venia/node_modules/sudo-prompt/index.js:329:27
       at tryToString (fs.js:514:3)
       at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:502:12) code: 1 },
  stdout: undefined,
  stderr: undefined } +3s
(node:98715) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Command failed: /Users/jorkvist/.nvm/versions/node/v8.5.0/bin/node /Users/jorkvist/PWARIBATEX/venia-pwa-concept/theme-frontend-venia/node_modules/@jzetlen/pwa-buildpack/dist/util/tmp7dd8habgbjggd && rm /Users/jorkvist/PWARIBATEX/venia-pwa-concept/theme-frontend-venia/node_modules/@jzetlen/pwa-buildpack/dist/util/tmp7dd8habgbjggd
module.js:473
      throw err;
      ^

Error: Cannot find module '/Users/jorkvist/PWARIBATEX/venia-pwa-concept/theme-frontend-venia/node_modules/@jzetlen/pwa-buildpack/dist/util/tmp7dd8habgbjggd'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:453:25)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:201:16)
    at bootstrap_node.js:626:3

(node:98715) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
  pwa-buildpack:util:run-as-root.js sudo /Users/jorkvist/.nvm/versions/node/v8.5.0/bin/node /Users/jorkvist/PWARIBATEX/venia-pwa-concept/theme-frontend-venia/node_modules/@jzetlen/pwa-buildpack/dist/util/tmpib0fh061188d && rm /Users/jorkvist/PWARIBATEX/venia-pwa-concept/theme-frontend-venia/node_modules/@jzetlen/pwa-buildpack/dist/util/tmpib0fh061188d returned { error: 
   { Error: Command failed: /Users/jorkvist/.nvm/versions/node/v8.5.0/bin/node /Users/jorkvist/PWARIBATEX/venia-pwa-concept/theme-frontend-venia/node_modules/@jzetlen/pwa-buildpack/dist/util/tmpib0fh061188d && rm /Users/jorkvist/PWARIBATEX/venia-pwa-concept/theme-frontend-venia/node_modules/@jzetlen/pwa-buildpack/dist/util/tmpib0fh061188d
   module.js:473
         throw err;
         ^
   
   Error: Cannot find module '/Users/jorkvist/PWARIBATEX/venia-pwa-concept/theme-frontend-venia/node_modules/@jzetlen/pwa-buildpack/dist/util/tmpib0fh061188d'
       at Function.Module._resolveFilename (module.js:527:15)
       at Function.Module._load (module.js:453:25)
       at Function.Module.runMain (module.js:665:10)
       at startup (bootstrap_node.js:201:16)
       at bootstrap_node.js:626:3
   
       at /Users/jorkvist/PWARIBATEX/venia-pwa-concept/theme-frontend-venia/node_modules/sudo-prompt/index.js:329:27
       at tryToString (fs.js:514:3)
       at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:502:12) code: 1 },
  stdout: undefined,
  stderr: undefined } +5s
Error: [pwa-buildpack:util:ssl-cert-store.js] Error generating dev certificate: Command failed: /Users/jorkvist/.nvm/versions/node/v8.5.0/bin/node /Users/jorkvist/PWARIBATEX/venia-pwa-concept/theme-frontend-venia/node_modules/@jzetlen/pwa-buildpack/dist/util/tmpib0fh061188d && rm /Users/jorkvist/PWARIBATEX/venia-pwa-concept/theme-frontend-venia/node_modules/@jzetlen/pwa-buildpack/dist/util/tmpib0fh061188d
module.js:473
      throw err;
      ^

Error: Cannot find module '/Users/jorkvist/PWARIBATEX/venia-pwa-concept/theme-frontend-venia/node_modules/@jzetlen/pwa-buildpack/dist/util/tmpib0fh061188d'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:453:25)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:201:16)
    at bootstrap_node.js:626:3
 Error: Command failed: /Users/jorkvist/.nvm/versions/node/v8.5.0/bin/node /Users/jorkvist/PWARIBATEX/venia-pwa-concept/theme-frontend-venia/node_modules/@jzetlen/pwa-buildpack/dist/util/tmpib0fh061188d && rm /Users/jorkvist/PWARIBATEX/venia-pwa-concept/theme-frontend-venia/node_modules/@jzetlen/pwa-buildpack/dist/util/tmpib0fh061188d
module.js:473
      throw err;
      ^

Error: Cannot find module '/Users/jorkvist/PWARIBATEX/venia-pwa-concept/theme-frontend-venia/node_modules/@jzetlen/pwa-buildpack/dist/util/tmpib0fh061188d'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:453:25)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:201:16)
    at bootstrap_node.js:626:3

    at /Users/jorkvist/PWARIBATEX/venia-pwa-concept/theme-frontend-venia/node_modules/sudo-prompt/index.js:329:27
    at tryToString (fs.js:514:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:502:12)
    at Object.create (/Users/jorkvist/PWARIBATEX/venia-pwa-concept/theme-frontend-venia/node_modules/@jzetlen/pwa-buildpack/dist/util/ssl-cert-store.js:44:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Mikaels-MBP-2:theme-frontend-venia jorkvist$ 
`

@zetlen i think Im getting the same error as @rossmc. Here is my log with extra output.

**Comment by rossmc** [comment]
Hi @zetlen, see below.

```
ross in ~/Projects/venia-pwa-concept/theme-frontend-venia
$ (master) DEBUG=pwa-buildpack:WebpackTools:*,pwa-buildpack:util:run-as-root.js npm start

> theme-frontend-venia@0.1.0 start /Users/ross/Projects/venia-pwa-concept/theme-frontend-venia
> webpack-dev-server --progress --color --env.phase development

  pwa-buildpack:WebpackTools:PWADevServer.js configure() invoked { publicPath: '/pub/static/frontend/Magento/venia/en_US',
  backendDomain: 'https://magento2.vagrant83',
  serviceWorkerFileName: 'sw.js',
  paths:
   { src: '/Users/ross/Projects/venia-pwa-concept/theme-frontend-venia/src',
     assets: '/Users/ross/Projects/venia-pwa-concept/theme-frontend-venia/web',
     output: '/Users/ross/Projects/venia-pwa-concept/theme-frontend-venia/web/js' },
  id: 'magento-venia' } +0ms
  pwa-buildpack:WebpackTools:PWADevServer.js provideDevHost('magento-venia') +3ms
  pwa-buildpack:WebpackTools:PWADevServer.js checking if magento-venia.local.pwadev is loopback +3ms
  pwa-buildpack:util:run-as-root.js elevating privileges for async name => {
  pwa-buildpack:util:run-as-root.js                 const devcert = require('@magento/devcert');
  pwa-buildpack:util:run-as-root.js                 const certs = await devcert(name);
  pwa-buildpack:util:run-as-root.js                 process.stdout.write(JSON.stringify(certs));
  pwa-buildpack:util:run-as-root.js             } +0ms
  pwa-buildpack:util:run-as-root.js running sudoPrompt("/usr/local/bin/node /Users/ross/Projects/venia-pwa-concept/theme-frontend-venia/node_modules/@magento/pwa-buildpack/dist/util/tmp006083iejh29ii8 && rm /Users/ross/Projects/venia-pwa-concept/theme-frontend-venia/node_modules/@magento/pwa-buildpack/dist/util/tmp006083iejh29ii8") now... +0ms
  pwa-buildpack:WebpackTools:PWADevServer.js setting magento-venia.local.pwadev loopback in /etc/hosts, may require password... +9ms
  pwa-buildpack:util:run-as-root.js elevating privileges for d => require('hostile').set('127.0.0.1', d) +7ms
  pwa-buildpack:util:run-as-root.js running sudoPrompt("/usr/local/bin/node /Users/ross/Projects/venia-pwa-concept/theme-frontend-venia/node_modules/@magento/pwa-buildpack/dist/util/tmp7hcb654e08a8b && rm /Users/ross/Projects/venia-pwa-concept/theme-frontend-venia/node_modules/@magento/pwa-buildpack/dist/util/tmp7hcb654e08a8b") now... +1ms
  pwa-buildpack:util:run-as-root.js sudo /usr/local/bin/node /Users/ross/Projects/venia-pwa-concept/theme-frontend-venia/node_modules/@magento/pwa-buildpack/dist/util/tmp006083iejh29ii8 && rm /Users/ross/Projects/venia-pwa-concept/theme-frontend-venia/node_modules/@magento/pwa-buildpack/dist/util/tmp006083iejh29ii8 returned { error:
   { Error: Command failed: /usr/local/bin/node /Users/ross/Projects/venia-pwa-concept/theme-frontend-venia/node_modules/@magento/pwa-buildpack/dist/util/tmp006083iejh29ii8 && rm /Users/ross/Projects/venia-pwa-concept/theme-frontend-venia/node_modules/@magento/pwa-buildpack/dist/util/tmp006083iejh29ii8
   module.js:491
       throw err;
       ^

   Error: Cannot find module '/Users/ross/Projects/venia-pwa-concept/theme-frontend-venia/node_modules/@magento/pwa-buildpack/dist/util/tmp006083iejh29ii8'
       at Function.Module._resolveFilename (module.js:489:15)
       at Function.Module._load (module.js:439:25)
       at Function.Module.runMain (module.js:609:10)
       at startup (bootstrap_node.js:158:16)
       at bootstrap_node.js:578:3

       at /Users/ross/Projects/venia-pwa-concept/theme-frontend-venia/node_modules/sudo-prompt/index.js:329:27
       at tryToString (fs.js:513:3)
       at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:501:12) code: 1 },
  stdout: undefined,
  stderr: undefined } +34s
Error: [pwa-buildpack:util:ssl-cert-store.js] Error generating dev certificate: Command failed: /usr/local/bin/node /Users/ross/Projects/venia-pwa-concept/theme-frontend-venia/node_modules/@magento/pwa-buildpack/dist/util/tmp006083iejh29ii8 && rm /Users/ross/Projects/venia-pwa-concept/theme-frontend-venia/node_modules/@magento/pwa-buildpack/dist/util/tmp006083iejh29ii8
module.js:491
    throw err;
    ^

Error: Cannot find module '/Users/ross/Projects/venia-pwa-concept/theme-frontend-venia/node_modules/@magento/pwa-buildpack/dist/util/tmp006083iejh29ii8'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:578:3
 Error: Command failed: /usr/local/bin/node /Users/ross/Projects/venia-pwa-concept/theme-frontend-venia/node_modules/@magento/pwa-buildpack/dist/util/tmp006083iejh29ii8 && rm /Users/ross/Projects/venia-pwa-concept/theme-frontend-venia/node_modules/@magento/pwa-buildpack/dist/util/tmp006083iejh29ii8
module.js:491
    throw err;
    ^

Error: Cannot find module '/Users/ross/Projects/venia-pwa-concept/theme-frontend-venia/node_modules/@magento/pwa-buildpack/dist/util/tmp006083iejh29ii8'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:578:3

    at /Users/ross/Projects/venia-pwa-concept/theme-frontend-venia/node_modules/sudo-prompt/index.js:329:27
    at tryToString (fs.js:513:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:501:12)
    at Object.create (/Users/ross/Projects/venia-pwa-concept/theme-frontend-venia/node_modules/@magento/pwa-buildpack/dist/util/ssl-cert-store.js:44:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

Don't know if it helps, but the PWA Studio requests my system password twice just after line 25, as in two dialog windows open looking for the password.

**Comment by philaturner** [comment]
adding an `await` into `run-as-root.js` seemed to progress mine

```js
const stdout = await sudoPromptToRunShell(`${process.argv[0]} ${scriptLoc} && rm ${scriptLoc}`);
```
seemed to help me out, not sure if helps others.  Not sure if super viable solution but worth a comment

**Comment by zetlen** [comment]
Thanks, @rossmc and @jorkvist. And @philaturner: Good catch! I made **two** dumb mistakes in this module, actually; I didn't await the result of the `sudoPromptToRunShell` call, _and_ I tried deleting the file twice in two different ways--both with the `&& rm` and with the `await` in a `finally` clause. In magento-research/pwa-buildpack/pull/28 I've fixed both issues in the most cross-compatible way I can. I'll make sure this is merged and released ASAP.

**Comment by rossmc** [comment]
awesome, I can see that fixes it.

Getting new console error when I open the site, but I'll investigate it first before opening a new issue.

```
resolveUnknownRoute.js?27f5:42 POST https://magento-venia.local.pwadev:8000/graphql 404 ()
```

Thanks, again :)

**Comment by matthewhaworth** [comment]
@rossmc you need to use Magento 2.3

**Comment by rossmc** [comment]
thanks @matthewhaworth, did you just use the [2.3-develop ](https://github.com/magento/magento2/tree/2.3-develop)branch?

Do you know if their any config changes on the admin panel I need to make for graphql to work?

**Comment by DrewML** [comment]
@rossmc no admin panel changes - being on `2.3-develop` should be enough. Are you getting a 404 on `/graphql`?

**Comment by matthewhaworth** [comment]
@rossmc GraphQL seemed to work fine out of the box for me, but I was getting a weird 404 if I was on the root. I did /home and it acknowledge it was a CMS_PAGE.
